import type { Metadata } from "next";
import { Spectral } from "next/font/google";
import "./globals.css";
import { StagewiseToolbar } from "@stagewise/toolbar-next";
import ReactPlugin from "@stagewise-plugins/react";

const spectral = Spectral({
  variable: "--font-spectral",
  subsets: ["latin"],
  weight: ["400", "600"],
  style: ["normal", "italic"],
});

// Adding Zen Antique Soft font from Google Fonts
const zenAntique = {
  variable: "--font-zen-antique",
  fontFamily: "'Zen Antique Soft', serif",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spectral.variable} antialiased`}
        suppressHydrationWarning
      >
        <link href="https://fonts.googleapis.com/css2?family=Zen+Antique+Soft:wght@400&display=swap" rel="stylesheet" />
        <StagewiseToolbar config={{ plugins: [ReactPlugin] }} />
        {children}
      </body>
    </html>
  );
}
